(* Dennis Cosgrove *)
CM.make "../unit_test/unit_test.cm";
use "../../../main/sml/hearts/hearts.sml";

signature TEST_HEARTS = sig
    val test_complete : unit -> unit
end

structure TestHearts :> TEST_HEARTS = struct
    open UnitTest

    fun test_is_card_valid() =
        ( enter("is_card_valid")

        ; assertTrue(is_card_valid(Clubs, Ace))
        ; assertTrue(is_card_valid(Clubs, King))
        ; assertTrue(is_card_valid(Clubs, Queen))
        ; assertTrue(is_card_valid(Clubs, Jack))
        ; assertTrue(is_card_valid(Clubs, Num 10))
        ; assertTrue(is_card_valid(Clubs, Num 9))
        ; assertTrue(is_card_valid(Clubs, Num 8))
        ; assertTrue(is_card_valid(Clubs, Num 7))
        ; assertTrue(is_card_valid(Clubs, Num 6))
        ; assertTrue(is_card_valid(Clubs, Num 5))
        ; assertTrue(is_card_valid(Clubs, Num 4))
        ; assertTrue(is_card_valid(Clubs, Num 3))
        ; assertTrue(is_card_valid(Clubs, Num 2))
        
        ; assertTrue(is_card_valid(Diamonds, Ace))
        ; assertTrue(is_card_valid(Diamonds, King))
        ; assertTrue(is_card_valid(Diamonds, Queen))
        ; assertTrue(is_card_valid(Diamonds, Jack))
        ; assertTrue(is_card_valid(Diamonds, Num 10))
        ; assertTrue(is_card_valid(Diamonds, Num 9))
        ; assertTrue(is_card_valid(Diamonds, Num 8))
        ; assertTrue(is_card_valid(Diamonds, Num 7))
        ; assertTrue(is_card_valid(Diamonds, Num 6))
        ; assertTrue(is_card_valid(Diamonds, Num 5))
        ; assertTrue(is_card_valid(Diamonds, Num 4))
        ; assertTrue(is_card_valid(Diamonds, Num 3))
        ; assertTrue(is_card_valid(Diamonds, Num 2))
        
        ; assertTrue(is_card_valid(Hearts, Ace))
        ; assertTrue(is_card_valid(Hearts, King))
        ; assertTrue(is_card_valid(Hearts, Queen))
        ; assertTrue(is_card_valid(Hearts, Jack))
        ; assertTrue(is_card_valid(Hearts, Num 10))
        ; assertTrue(is_card_valid(Hearts, Num 9))
        ; assertTrue(is_card_valid(Hearts, Num 8))
        ; assertTrue(is_card_valid(Hearts, Num 7))
        ; assertTrue(is_card_valid(Hearts, Num 6))
        ; assertTrue(is_card_valid(Hearts, Num 5))
        ; assertTrue(is_card_valid(Hearts, Num 4))
        ; assertTrue(is_card_valid(Hearts, Num 3))
        ; assertTrue(is_card_valid(Hearts, Num 2))
        
        ; assertTrue(is_card_valid(Spades, Ace))
        ; assertTrue(is_card_valid(Spades, King))
        ; assertTrue(is_card_valid(Spades, Queen))
        ; assertTrue(is_card_valid(Spades, Jack))
        ; assertTrue(is_card_valid(Spades, Num 10))
        ; assertTrue(is_card_valid(Spades, Num 9))
        ; assertTrue(is_card_valid(Spades, Num 8))
        ; assertTrue(is_card_valid(Spades, Num 7))
        ; assertTrue(is_card_valid(Spades, Num 6))
        ; assertTrue(is_card_valid(Spades, Num 5))
        ; assertTrue(is_card_valid(Spades, Num 4))
        ; assertTrue(is_card_valid(Spades, Num 3))
        ; assertTrue(is_card_valid(Spades, Num 2))

        (* number cards outside of 2 and 10 inclusive are not valid *)
        ; assertFalse(is_card_valid(Spades, Num 1))
        ; assertFalse(is_card_valid(Spades, Num 11))
        ; assertFalse(is_card_valid(Spades, Num 425))
        ; assertFalse(is_card_valid(Spades, Num ~10))

        ; assertFalse(is_card_valid(Hearts, Num 1))
        ; assertFalse(is_card_valid(Hearts, Num 11))
        ; assertFalse(is_card_valid(Hearts, Num 425))
        ; assertFalse(is_card_valid(Hearts, Num ~10))

        ; assertFalse(is_card_valid(Diamonds, Num 1))
        ; assertFalse(is_card_valid(Diamonds, Num 11))
        ; assertFalse(is_card_valid(Diamonds, Num 425))
        ; assertFalse(is_card_valid(Diamonds, Num ~10))

        ; assertFalse(is_card_valid(Clubs, Num 1))
        ; assertFalse(is_card_valid(Clubs, Num 11))
        ; assertFalse(is_card_valid(Clubs, Num 425))
        ; assertFalse(is_card_valid(Clubs, Num ~10))

        ; leave()
        )

    val INVALID_CARD = (Spades, Num(231))

    fun test_are_all_cards_valid() =
        ( enter("are_all_cards_valid")
        ; assertTrue(are_all_cards_valid([]))
        ; assertTrue(are_all_cards_valid([(Spades, Ace)]))
        ; assertTrue(are_all_cards_valid([(Spades, Ace), (Diamonds, King)]))
        ; assertTrue(are_all_cards_valid([(Spades, Ace), (Diamonds, King), (Clubs, Num(7))]))
        ; assertTrue(are_all_cards_valid([(Spades, Ace), (Diamonds, King), (Clubs, Num(7)), (Clubs, Num(2))]))
        ; assertFalse(are_all_cards_valid([INVALID_CARD]))
        ; assertFalse(are_all_cards_valid([INVALID_CARD, (Spades, Ace)]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), INVALID_CARD]))
        ; assertFalse(are_all_cards_valid([INVALID_CARD, (Spades, Ace), (Diamonds, King)]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), INVALID_CARD, (Diamonds, King)]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), (Diamonds, King), INVALID_CARD]))
        ; assertFalse(are_all_cards_valid([INVALID_CARD, (Spades, Ace), (Diamonds, King), (Clubs, Num(7))]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), INVALID_CARD, (Diamonds, King), (Clubs, Num(7))]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), (Diamonds, King), INVALID_CARD, (Clubs, Num(7))]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), (Diamonds, King), (Clubs, Num(7)), INVALID_CARD]))
        ; assertFalse(are_all_cards_valid([INVALID_CARD, (Spades, Ace), (Diamonds, King), (Clubs, Num(7)), (Clubs, Num(2))]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), INVALID_CARD, (Diamonds, King), (Clubs, Num(7)), (Clubs, Num(2))]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), (Diamonds, King), INVALID_CARD, (Clubs, Num(7)), (Clubs, Num(2))]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), (Diamonds, King), (Clubs, Num(7)), INVALID_CARD, (Clubs, Num(2))]))
        ; assertFalse(are_all_cards_valid([(Spades, Ace), (Diamonds, King), (Clubs, Num(7)), (Clubs, Num(2)), INVALID_CARD]))
        ; assertFalse(are_all_cards_valid([INVALID_CARD, INVALID_CARD, (Spades, Ace), INVALID_CARD, (Diamonds, King), INVALID_CARD, (Clubs, Num(7)), INVALID_CARD, INVALID_CARD, (Clubs, Num(2)), INVALID_CARD]))
        ; leave()
        )

    (* ======================================================== *)
    (* NOTE: all tests from here on will only pass valid cards. *)
    (*       you need NOT check for validity or handle invalid cards from here on. *)
    (* ======================================================== *)
    fun test_card_score() =
        ( enter("card_score")
        ; assertEquals_Int(13, card_score(Spades, Queen))
        ; assertEquals_Int(1, card_score(Hearts, Ace))
        ; assertEquals_Int(1, card_score(Hearts, King))
        ; assertEquals_Int(1, card_score(Hearts, Queen))
        ; assertEquals_Int(1, card_score(Hearts, Jack))
        ; assertEquals_Int(1, card_score(Hearts, Num 10))
        ; assertEquals_Int(1, card_score(Hearts, Num 9))
        ; assertEquals_Int(1, card_score(Hearts, Num 8))
        ; assertEquals_Int(1, card_score(Hearts, Num 7))
        ; assertEquals_Int(1, card_score(Hearts, Num 6))
        ; assertEquals_Int(1, card_score(Hearts, Num 5))
        ; assertEquals_Int(1, card_score(Hearts, Num 4))
        ; assertEquals_Int(1, card_score(Hearts, Num 3))
        ; assertEquals_Int(1, card_score(Hearts, Num 2))
        ; assertEquals_Int(~10, card_score(Diamonds, Jack))
        
        ; assertEquals_Int(0, card_score(Clubs, Ace))
        ; assertEquals_Int(0, card_score(Clubs, King))
        ; assertEquals_Int(0, card_score(Clubs, Queen))
        ; assertEquals_Int(0, card_score(Clubs, Jack))
        ; assertEquals_Int(0, card_score(Clubs, Num 10))
        ; assertEquals_Int(0, card_score(Clubs, Num 9))
        ; assertEquals_Int(0, card_score(Clubs, Num 8))
        ; assertEquals_Int(0, card_score(Clubs, Num 7))
        ; assertEquals_Int(0, card_score(Clubs, Num 6))
        ; assertEquals_Int(0, card_score(Clubs, Num 5))
        ; assertEquals_Int(0, card_score(Clubs, Num 4))
        ; assertEquals_Int(0, card_score(Clubs, Num 3))
        ; assertEquals_Int(0, card_score(Clubs, Num 2))
        
        ; assertEquals_Int(0, card_score(Diamonds, Ace))
        ; assertEquals_Int(0, card_score(Diamonds, King))
        ; assertEquals_Int(0, card_score(Diamonds, Queen))
        
        ; assertEquals_Int(0, card_score(Diamonds, Num 10))
        ; assertEquals_Int(0, card_score(Diamonds, Num 9))
        ; assertEquals_Int(0, card_score(Diamonds, Num 8))
        ; assertEquals_Int(0, card_score(Diamonds, Num 7))
        ; assertEquals_Int(0, card_score(Diamonds, Num 6))
        ; assertEquals_Int(0, card_score(Diamonds, Num 5))
        ; assertEquals_Int(0, card_score(Diamonds, Num 4))
        ; assertEquals_Int(0, card_score(Diamonds, Num 3))
        ; assertEquals_Int(0, card_score(Diamonds, Num 2))
        
        ; assertEquals_Int(0, card_score(Spades, Ace))
        ; assertEquals_Int(0, card_score(Spades, King))

        ; assertEquals_Int(0, card_score(Spades, Jack))
        ; assertEquals_Int(0, card_score(Spades, Num 10))
        ; assertEquals_Int(0, card_score(Spades, Num 9))
        ; assertEquals_Int(0, card_score(Spades, Num 8))
        ; assertEquals_Int(0, card_score(Spades, Num 7))
        ; assertEquals_Int(0, card_score(Spades, Num 6))
        ; assertEquals_Int(0, card_score(Spades, Num 5))
        ; assertEquals_Int(0, card_score(Spades, Num 4))
        ; assertEquals_Int(0, card_score(Spades, Num 3))
        ; assertEquals_Int(0, card_score(Spades, Num 2))
        ; leave()
        )

    val all_clubs = [(Clubs, Ace), (Clubs, King), (Clubs, Queen), (Clubs, Jack), (Clubs, Num(10)), (Clubs, Num(9)), (Clubs, Num(8)), (Clubs, Num(7)), (Clubs, Num(6)), (Clubs, Num(5)), (Clubs, Num(4)), (Clubs, Num(3)), (Clubs, Num(2))]
    val all_diamonds = [(Diamonds, Ace), (Diamonds, King), (Diamonds, Queen), (Diamonds, Jack), (Diamonds, Num(10)), (Diamonds, Num(9)), (Diamonds, Num(8)), (Diamonds, Num(7)), (Diamonds, Num(6)), (Diamonds, Num(5)), (Diamonds, Num(4)), (Diamonds, Num(3)), (Diamonds, Num(2))]
    val all_hearts = [(Hearts, Ace), (Hearts, King), (Hearts, Queen), (Hearts, Jack), (Hearts, Num(10)), (Hearts, Num(9)), (Hearts, Num(8)), (Hearts, Num(7)), (Hearts, Num(6)), (Hearts, Num(5)), (Hearts, Num(4)), (Hearts, Num(3)), (Hearts, Num(2))]
    val all_spades = [(Spades, Ace), (Spades, King), (Spades, Queen), (Spades, Jack), (Spades, Num(10)), (Spades, Num(9)), (Spades, Num(8)), (Spades, Num(7)), (Spades, Num(6)), (Spades, Num(5)), (Spades, Num(4)), (Spades, Num(3)), (Spades, Num(2))]

    val all_aces = [(Clubs, Ace), (Diamonds, Ace), (Hearts, Ace), (Spades, Ace)]
    val all_kings = [(Clubs, King), (Diamonds, King), (Hearts, King), (Spades, King)]
    val all_queens = [(Clubs, Queen), (Diamonds, Queen), (Hearts, Queen), (Spades, Queen)]
    val all_jacks = [(Clubs, Jack), (Diamonds, Jack), (Hearts, Jack), (Spades, Jack)]
    val all_10s = [(Clubs, Num(10)), (Diamonds, Num(10)), (Hearts, Num(10)), (Spades, Num(10))]
    val all_9s = [(Clubs, Num(9)), (Diamonds, Num(9)), (Hearts, Num(9)), (Spades, Num(9))]
    val all_8s = [(Clubs, Num(8)), (Diamonds, Num(8)), (Hearts, Num(8)), (Spades, Num(8))]
    val all_7s = [(Clubs, Num(7)), (Diamonds, Num(7)), (Hearts, Num(7)), (Spades, Num(7))]
    val all_6s = [(Clubs, Num(6)), (Diamonds, Num(6)), (Hearts, Num(6)), (Spades, Num(6))]
    val all_5s = [(Clubs, Num(5)), (Diamonds, Num(5)), (Hearts, Num(5)), (Spades, Num(5))]
    val all_4s = [(Clubs, Num(4)), (Diamonds, Num(4)), (Hearts, Num(4)), (Spades, Num(4))]
    val all_3s = [(Clubs, Num(3)), (Diamonds, Num(3)), (Hearts, Num(3)), (Spades, Num(3))]
    val all_2s = [(Clubs, Num(2)), (Diamonds, Num(2)), (Hearts, Num(2)), (Spades, Num(2))]

    fun test_total_score_of_card_list() =
        ( enter("total_score_of_card_list")
        ; assertEquals_Int(0, total_score_of_card_list([]))
        ; assertEquals_Int(13, total_score_of_card_list([(Spades, Queen)]))
        ; assertEquals_Int(1, total_score_of_card_list([(Hearts, King)]))
        ; assertEquals_Int(~10, total_score_of_card_list([(Diamonds, Jack)]))
        ; assertEquals_Int(0, total_score_of_card_list([(Clubs, Ace)]))
        ; assertEquals_Int(0, total_score_of_card_list(all_clubs))
        ; assertEquals_Int(~10, total_score_of_card_list(all_diamonds))
        ; assertEquals_Int(13, total_score_of_card_list(all_hearts))
        ; assertEquals_Int(13, total_score_of_card_list(all_spades))
        ; assertEquals_Int(1, total_score_of_card_list(all_aces))
        ; assertEquals_Int(1, total_score_of_card_list(all_kings))
        ; assertEquals_Int(14, total_score_of_card_list(all_queens))
        ; assertEquals_Int(~9, total_score_of_card_list(all_jacks))
        ; assertEquals_Int(1, total_score_of_card_list(all_10s))
        ; assertEquals_Int(1, total_score_of_card_list(all_9s))
        ; assertEquals_Int(1, total_score_of_card_list(all_8s))
        ; assertEquals_Int(1, total_score_of_card_list(all_7s))
        ; assertEquals_Int(1, total_score_of_card_list(all_6s))
        ; assertEquals_Int(1, total_score_of_card_list(all_5s))
        ; assertEquals_Int(1, total_score_of_card_list(all_4s))
        ; assertEquals_Int(1, total_score_of_card_list(all_3s))
        ; assertEquals_Int(1, total_score_of_card_list(all_2s))
        ; leave()
        )
       
    (* ======================================================== *)
    (* NOTE: total_score_of_player_list must be tail recursive. *)
    (* ======================================================== *)

    fun test_total_score_of_player_list() =
        ( enter("total_score_of_player_list")
        ; assertEquals_Int(0, total_score_of_player_list([]))
        ; assertEquals_Int(0, total_score_of_player_list([[]]))
        ; assertEquals_Int(0, total_score_of_player_list([[],[]]))
        ; assertEquals_Int(0, total_score_of_player_list([[],[],[]]))
        ; assertEquals_Int(13, total_score_of_player_list([[(Spades, Queen)]]))
        ; assertEquals_Int(1, total_score_of_player_list([[(Hearts, King)]]))
        ; assertEquals_Int(~10, total_score_of_player_list([[(Diamonds, Jack)]]))
        ; assertEquals_Int(0, total_score_of_player_list([[(Clubs, Ace)]]))
        ; assertEquals_Int(0, total_score_of_player_list([all_clubs]))
        ; assertEquals_Int(~10, total_score_of_player_list([all_diamonds]))
        ; assertEquals_Int(13, total_score_of_player_list([all_hearts]))
        ; assertEquals_Int(13, total_score_of_player_list([all_spades]))
        ; assertEquals_Int(1, total_score_of_player_list([all_aces]))
        ; assertEquals_Int(1, total_score_of_player_list([all_kings]))
        ; assertEquals_Int(14, total_score_of_player_list([all_queens]))
        ; assertEquals_Int(~9, total_score_of_player_list([all_jacks]))
        ; assertEquals_Int(1, total_score_of_player_list([all_10s]))
        ; assertEquals_Int(1, total_score_of_player_list([all_9s]))
        ; assertEquals_Int(1, total_score_of_player_list([all_8s]))
        ; assertEquals_Int(1, total_score_of_player_list([all_7s]))
        ; assertEquals_Int(1, total_score_of_player_list([all_6s]))
        ; assertEquals_Int(1, total_score_of_player_list([all_5s]))
        ; assertEquals_Int(1, total_score_of_player_list([all_4s]))
        ; assertEquals_Int(1, total_score_of_player_list([all_3s]))
        ; assertEquals_Int(1, total_score_of_player_list([all_2s]))
        ; assertEquals_Int(~10, total_score_of_player_list([all_clubs, all_diamonds]))
        ; assertEquals_Int(3, total_score_of_player_list([all_diamonds, all_hearts]))
        ; assertEquals_Int(26, total_score_of_player_list([all_hearts, all_spades]))
        ; assertEquals_Int(16, total_score_of_player_list([all_diamonds, all_hearts, all_spades]))
        ; assertEquals_Int(16, total_score_of_player_list([all_clubs, all_diamonds, all_hearts, all_spades]))
        ; assertEquals_Int(2, total_score_of_player_list([all_7s, all_2s]))
        ; assertEquals_Int(2, total_score_of_player_list([all_aces, all_kings]))
        ; assertEquals_Int(15, total_score_of_player_list([all_aces, all_queens]))
        ; assertEquals_Int(~8, total_score_of_player_list([all_aces, all_jacks]))
        ; assertEquals_Int(16, total_score_of_player_list([all_aces, all_kings, all_queens]))
        ; assertEquals_Int(7, total_score_of_player_list([all_aces, all_kings, all_queens, all_jacks]))
        ; assertEquals_Int(16, total_score_of_player_list([all_aces, all_kings, all_queens, all_jacks, all_10s, all_9s, all_8s, all_7s, all_6s, all_5s, all_4s, all_3s, all_2s]))
        ; assertEquals_Int(16, total_score_of_player_list([[], all_aces, all_kings, all_queens, all_jacks, all_10s, all_9s, all_8s, all_7s, all_6s, all_5s, all_4s, all_3s, all_2s]))
        ; assertEquals_Int(16, total_score_of_player_list([all_aces, all_kings, all_queens, all_jacks, all_10s, [], all_9s, all_8s, all_7s, all_6s, all_5s, all_4s, all_3s, all_2s]))
        ; assertEquals_Int(16, total_score_of_player_list([all_aces, all_kings, all_queens, all_jacks, all_10s, all_9s, all_8s, all_7s, all_6s, all_5s, all_4s, all_3s, all_2s, []]))
        ; leave()
        )

    (* ======================================================== *)
    (* NOTE: total_card_count_for_all_players may use length.   *)
    (* ======================================================== *)

    (* ======================================================== *)
    (* NOTE: total_card_count_for_all_players must use a higher order function. *)
    (* ======================================================== *)
    fun test_total_card_count_for_all_players() =
        ( enter("total_card_count_for_all_players")
        ; assertEquals_Int(0, total_card_count_for_all_players([]))
        ; assertEquals_Int(0, total_card_count_for_all_players([[]]))
        ; assertEquals_Int(0, total_card_count_for_all_players([[],[]]))
        ; assertEquals_Int(0, total_card_count_for_all_players([[],[],[]]))
        ; assertEquals_Int(1, total_card_count_for_all_players([[(Spades, Queen)]]))
        ; assertEquals_Int(1, total_card_count_for_all_players([[(Hearts, King)]]))
        ; assertEquals_Int(1, total_card_count_for_all_players([[(Diamonds, Jack)]]))
        ; assertEquals_Int(1, total_card_count_for_all_players([[(Clubs, Ace)]]))
        ; assertEquals_Int(13, total_card_count_for_all_players([all_clubs]))
        ; assertEquals_Int(13, total_card_count_for_all_players([all_diamonds]))
        ; assertEquals_Int(13, total_card_count_for_all_players([all_hearts]))
        ; assertEquals_Int(13, total_card_count_for_all_players([all_spades]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_aces]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_kings]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_queens]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_jacks]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_10s]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_9s]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_8s]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_7s]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_6s]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_5s]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_4s]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_3s]))
        ; assertEquals_Int(4, total_card_count_for_all_players([all_2s]))
        ; assertEquals_Int(26, total_card_count_for_all_players([all_clubs, all_diamonds]))
        ; assertEquals_Int(26, total_card_count_for_all_players([all_diamonds, all_hearts]))
        ; assertEquals_Int(26, total_card_count_for_all_players([all_hearts, all_spades]))
        ; assertEquals_Int(39, total_card_count_for_all_players([all_diamonds, all_hearts, all_spades]))
        ; assertEquals_Int(52, total_card_count_for_all_players([all_clubs, all_diamonds, all_hearts, all_spades]))
        ; assertEquals_Int(8, total_card_count_for_all_players([all_7s, all_2s]))
        ; assertEquals_Int(8, total_card_count_for_all_players([all_aces, all_kings]))
        ; assertEquals_Int(8, total_card_count_for_all_players([all_aces, all_queens]))
        ; assertEquals_Int(8, total_card_count_for_all_players([all_aces, all_jacks]))
        ; assertEquals_Int(12, total_card_count_for_all_players([all_aces, all_kings, all_queens]))
        ; assertEquals_Int(16, total_card_count_for_all_players([all_aces, all_kings, all_queens, all_jacks]))
        ; assertEquals_Int(52, total_card_count_for_all_players([all_aces, all_kings, all_queens, all_jacks, all_10s, all_9s, all_8s, all_7s, all_6s, all_5s, all_4s, all_3s, all_2s]))
        ; leave()
        )

    fun test_is_correct_total_of_cards() =
        ( enter("is_correct_total_of_cards")
        ; assertFalse(is_correct_total_of_cards([]))
        ; assertFalse(is_correct_total_of_cards([[]]))
        ; assertFalse(is_correct_total_of_cards([[],[]]))
        ; assertFalse(is_correct_total_of_cards([[],[],[]]))
        ; assertFalse(is_correct_total_of_cards([[(Spades, Queen)]]))
        ; assertFalse(is_correct_total_of_cards([[(Hearts, King)]]))
        ; assertFalse(is_correct_total_of_cards([[(Diamonds, Jack)]]))
        ; assertFalse(is_correct_total_of_cards([[(Clubs, Ace)]]))
        ; assertFalse(is_correct_total_of_cards([all_clubs]))
        ; assertFalse(is_correct_total_of_cards([all_diamonds]))
        ; assertFalse(is_correct_total_of_cards([all_hearts]))
        ; assertFalse(is_correct_total_of_cards([all_spades]))
        ; assertFalse(is_correct_total_of_cards([all_aces]))
        ; assertFalse(is_correct_total_of_cards([all_kings]))
        ; assertFalse(is_correct_total_of_cards([all_queens]))
        ; assertFalse(is_correct_total_of_cards([all_jacks]))
        ; assertFalse(is_correct_total_of_cards([all_10s]))
        ; assertFalse(is_correct_total_of_cards([all_9s]))
        ; assertFalse(is_correct_total_of_cards([all_8s]))
        ; assertFalse(is_correct_total_of_cards([all_7s]))
        ; assertFalse(is_correct_total_of_cards([all_6s]))
        ; assertFalse(is_correct_total_of_cards([all_5s]))
        ; assertFalse(is_correct_total_of_cards([all_4s]))
        ; assertFalse(is_correct_total_of_cards([all_3s]))
        ; assertFalse(is_correct_total_of_cards([all_2s]))
        ; assertFalse(is_correct_total_of_cards([all_clubs, all_diamonds]))
        ; assertFalse(is_correct_total_of_cards([all_diamonds, all_hearts]))
        ; assertFalse(is_correct_total_of_cards([all_hearts, all_spades]))
        ; assertFalse(is_correct_total_of_cards([all_diamonds, all_hearts, all_spades]))
        ; assertTrue(is_correct_total_of_cards([all_clubs, all_diamonds, all_hearts, all_spades]))
        ; assertFalse(is_correct_total_of_cards([all_7s, all_2s]))
        ; assertFalse(is_correct_total_of_cards([all_aces, all_kings]))
        ; assertFalse(is_correct_total_of_cards([all_aces, all_queens]))
        ; assertFalse(is_correct_total_of_cards([all_aces, all_jacks]))
        ; assertFalse(is_correct_total_of_cards([all_aces, all_kings, all_queens]))
        ; assertFalse(is_correct_total_of_cards([all_aces, all_kings, all_queens, all_jacks]))
        ; assertTrue(is_correct_total_of_cards([all_aces, all_kings, all_queens, all_jacks, all_10s, all_9s, all_8s, all_7s, all_6s, all_5s, all_4s, all_3s, all_2s]))
        ; leave()
        )


    fun test_is_shenanigans_detected() =
        ( enter("is_shenanigans_detected")
        ; assertTrue(is_shenanigans_detected([]))
        ; assertTrue(is_shenanigans_detected([[]]))
        ; assertTrue(is_shenanigans_detected([[],[]]))
        ; assertTrue(is_shenanigans_detected([[],[],[]]))
        ; assertTrue(is_shenanigans_detected([[(Spades, Queen)]]))
        ; assertTrue(is_shenanigans_detected([[(Hearts, King)]]))
        ; assertTrue(is_shenanigans_detected([[(Diamonds, Jack)]]))
        ; assertTrue(is_shenanigans_detected([[(Clubs, Ace)]]))
        ; assertTrue(is_shenanigans_detected([all_clubs]))
        ; assertTrue(is_shenanigans_detected([all_diamonds]))
        ; assertTrue(is_shenanigans_detected([all_hearts]))
        ; assertTrue(is_shenanigans_detected([all_spades]))
        ; assertTrue(is_shenanigans_detected([all_aces]))
        ; assertTrue(is_shenanigans_detected([all_kings]))
        ; assertTrue(is_shenanigans_detected([all_queens]))
        ; assertTrue(is_shenanigans_detected([all_jacks]))
        ; assertTrue(is_shenanigans_detected([all_10s]))
        ; assertTrue(is_shenanigans_detected([all_9s]))
        ; assertTrue(is_shenanigans_detected([all_8s]))
        ; assertTrue(is_shenanigans_detected([all_7s]))
        ; assertTrue(is_shenanigans_detected([all_6s]))
        ; assertTrue(is_shenanigans_detected([all_5s]))
        ; assertTrue(is_shenanigans_detected([all_4s]))
        ; assertTrue(is_shenanigans_detected([all_3s]))
        ; assertTrue(is_shenanigans_detected([all_2s]))
        ; assertTrue(is_shenanigans_detected([all_clubs, all_diamonds]))
        ; assertTrue(is_shenanigans_detected([all_diamonds, all_hearts]))
        ; assertTrue(is_shenanigans_detected([all_hearts, all_spades]))

        (* ======================================================== *)
        (* note: there are missing cards, but we fail to detect shenanigans due to all missing Clubs would count for 0 points anyway, so we get the expected result of 16 *)
        ; assertFalse(is_shenanigans_detected([all_diamonds, all_hearts, all_spades])) 
        (* ======================================================== *)
        
        
        ; assertFalse(is_shenanigans_detected([all_clubs, all_diamonds, all_hearts, all_spades]))
        ; assertTrue(is_shenanigans_detected([all_7s, all_2s]))
        ; assertTrue(is_shenanigans_detected([all_aces, all_kings]))
        ; assertTrue(is_shenanigans_detected([all_aces, all_queens]))
        ; assertTrue(is_shenanigans_detected([all_aces, all_jacks]))

        (* ======================================================== *)
        (* note: there are missing cards, but we fail to detect shenanigans due to the ten missing Hearts are counter balanced by the missing Jack of Diamonds, so we get the expected result of 16 *)
        ; assertFalse(is_shenanigans_detected([all_aces, all_kings, all_queens]))
        (* ======================================================== *)

        ; assertTrue(is_shenanigans_detected([all_aces, all_kings, all_queens, all_jacks]))
        ; assertFalse(is_shenanigans_detected([all_aces, all_kings, all_queens, all_jacks, all_10s, all_9s, all_8s, all_7s, all_6s, all_5s, all_4s, all_3s, all_2s]))
        ; leave()
        )

    fun test_complete() =
        ( test_is_card_valid()
        ; test_are_all_cards_valid()
        ; test_card_score()
        ; test_total_score_of_card_list()
        ; test_total_score_of_player_list()
        ; test_total_card_count_for_all_players()
        ; test_is_correct_total_of_cards()
        ; test_is_shenanigans_detected()
        )
end

val _ = ( UnitTest.processCommandLineArgs()
        ; TestHearts.test_complete()
        ; OS.Process.exit(OS.Process.success)
        )
