require_relative '../part_b/part_b_transforms_test'
require_relative '../part_b/part_b_class_hierarchy_and_method_definitions_unit_test'
require_relative '../part_b/part_b_push_component_test'
require_relative '../part_b/part_b_scene_background_test'
require_relative 'part_b_bare_bones_components_image_diff_unit_test'
require_relative 'part_b_bare_bones_composites_image_diff_unit_test'
